# Generated by Django 4.2.4 on 2024-06-22 19:49

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_blogmodel_is_active_blogmodel_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='description2',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
