# Generated by Django 4.1.13 on 2024-08-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0006_dietarypreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='allergens',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='DietaryPreference',
        ),
    ]
